version: "3.8"

services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "8000:8000"
    volumes:
      - ./BackEnd:/app
      - /app/node_modules
    env_file:
      - ./BackEnd/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  adminpage:
    build:
      context: ./admin_page
    ports:
      - "3001:3001"
    volumes:
      - ./admin_page:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
